name: studion_mobile
description: For photostudios searching

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.1
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  loading_indicator: ^3.0.2
  carousel_slider: ^4.0.0
  expandable_text: ^2.2.0
  card_swiper: ^2.0.4
  modal_bottom_sheet: ^2.0.0
  grouped_list: ^5.1.2
  line_icons: ^2.0.1
  skeleton_text: ^3.0.0
  url_launcher: ^6.0.12
  shared_preferences: ^2.0.8
  flutter_phone_direct_caller: ^2.1.0
  firebase_crashlytics: ^3.0.6
  firebase_analytics: ^10.0.6
  expandable: ^5.0.1
  firebase_messaging: ^14.1.1
  syncfusion_flutter_sliders: ^20.2.50

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.9

flutter_native_splash:
  background_image: "assets/splash.png"
  image: "assets/splash.png"
  android_gravity: fill_vertical
  ios_content_mode: scaleAspectFill
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
        - asset: assets/fonts/mulish/Mulish-BoldItalic.ttf
        - asset: assets/fonts/mulish/Mulish-ExtraBold.ttf
        - asset: assets/fonts/mulish/Mulish-ExtraBoldItalic.ttf
        - asset: assets/fonts/mulish/Mulish-Italic.ttf
        - asset: assets/fonts/mulish/Mulish-Light.ttf
        - asset: assets/fonts/mulish/Mulish-LightItalic.ttf
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
        - asset: assets/fonts/mulish/Mulish-MediumItalic.ttf
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
        - asset: assets/fonts/mulish/Mulish-SemiBoldItalic.ttf
